/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/** https://adventofcode.com/2022/day/2 */
class Day2Test {

  static Stream<Arguments> args() throws Exception {
    return Stream.of(
        Arguments.of(
            """
            A Y
            B X
            C Z
            """
                .replace("\n$", "")
                .lines(),
            15));
  }

  int solve(Stream<String> lines) {
    return 0;
  }

  @ParameterizedTest
  @MethodSource("args")
  void test(Stream<String> lines, int expected) throws Exception {
    assertEquals(expected, solve(lines));
  }
}
