/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/** https://adventofcode.com/2022/day/7 */
class Day7Test {

  static Stream<Arguments> args() throws Exception {
    return Stream.of(
        Arguments.of(
            """
            $ cd /
            $ ls
            dir a
            14848514 b.txt
            8504156 c.dat
            dir d
            $ cd a
            $ ls
            dir e
            29116 f
            2557 g
            62596 h.lst
            $ cd e
            $ ls
            584 i
            $ cd ..
            $ cd ..
            $ cd d
            $ ls
            4060174 j
            8033020 d.log
            5626152 d.ext
            7214296 k"""
                .lines(),
            95_437,
            true));
  }

  // sealed interface Filesystem permits File, Directory {
  //   long size();
  // }

  // record File(String name, long size) implements Filesystem {}

  // record Directory(String name, List<Filesystem> fs) implements Filesystem {
  //   public long size() {
  //     return fs.stream().reduce(0, (total, elem) -> total + elem.size(), Integer::sum);
  //   }
  // }

  int solve(Stream<String> line, boolean partOne) {
    return 0;
  }

  @ParameterizedTest
  @MethodSource("args")
  void test(Stream<String> lines, int expected, boolean partOne) throws Exception {
    assertEquals(expected, solve(lines, partOne));
  }
}
